version: '3.9'
services:
  scheduler-master:
    container_name: scheduler-master
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./scheduler
    volumes:
      - ./scheduler:/app
    env_file:
      - .env
    environment:
      SCHEDULER_NODE: master
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - default

  scheduler-worker:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./scheduler
    volumes:
      - ./scheduler:/app
    env_file:
      - .env
    environment:
      SCHEDULER_NODE: worker
    deploy:
      replicas: 6
      restart_policy:
        condition: on-failure
    depends_on:
      - scheduler-master
    networks:
      - default

  scheduler-client:
    container_name: scheduler-client
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: ./scheduler-client
    volumes:
      - ./scheduler-client:/app
    env_file:
      - .env
    ports:
      - 8080:3000
    networks:
      - default

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - default
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq